title: Heeuk Kang
email: gmldnr96@gmail.com
description: Personal website of Heeuk
url: "https://heeeeuk.com"
twitter: usernamewithoutatsymbol

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-admin
