title: Heeuk Kang
email: gmldnr96@gmail.com
description: Hello guys!
url: "https://heeeeuk.com"
twitter: usernamewithoutatsymbol

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed
